KokenSSOに対応
ueckoken/KM4K pull request #11
Opened 2023-02-07 10:03 UTC by csenet

https://github.com/ueckoken/card-manager
にて開発中のCard Managerとの統合を実装
どちらかで登録されていた場合に認証を通すようにしている

2023-02-08 15:29 UTC, Azuki-bar commented
テストが落ちているのなんでだろう
見てみます

2023-02-08 23:18 UTC, csenet commented
ありがとうございます

2023-02-09 03:45 UTC, Azuki-bar requested changes
少し変更要求だしました！

2023-02-09 03:45 UTC, Azuki-bar commented on KM4K.py
> +    if(status['verified']!= None and status['verified'] == True):
[nits]
```suggestion
    if status['verified'] is not None and status['verified']:
```
って書き変えると良いと思います。
Noneに対する比較は`==`ではなく`is`を用いて行います。

2023-02-09 03:45 UTC, Azuki-bar commented on KM4K.py
> +      'x-api-key': os.environ["API_KEY"],
[nits]
ヘッダのキーは次のように記載するルールがあったと記憶しています
`X-Api-Key`
```suggestion
      'X-Api-Key': os.environ["API_KEY"],
```

2023-02-09 03:45 UTC, Azuki-bar commented on KM4K.py
> +    url = "https://card.ueckoken.club/api/card/verify"
[must]
この値は環境変数から入れたいですね

このリポジトリは一応publicになっているので……

2023-02-09 03:55 UTC, csenet commented
Card Managerの方は正常に動いてそうなので、良さそうなら実機に組み込めそう
(Raspberry piへのDeploy方法が不明なので教えて欲しいです)

2023-02-09 04:05 UTC, Azuki-bar approved these changes
LGTMです！
テスト修正PRがマージされたらこのブランチに取り込んで上げてください

デプロイは暖かみのある手動git pullです
がんばってください

2023-02-09 08:06 UTC, merged